# SQLite version 3.x
#   gem install sqlite3-ruby (not necessary on OS X Leopard)

development: &default
  adapter: mysql2
  database: rebirth_development
  pool: 5
  timeout: 5000
  user: root
  host: localhost
  password: Password123#@!

test: &test
  <<: *default
  database: pairwise_test

cucumber:
  <<: *test

